#!/usr/bin/env bash
#
# run.sh — brings up NATS + the callout in the foreground (Ctrl-C to stop).
#
# It joins the two configuration sources: nats/.env (what a person decides) and
# nats/out/callout-env.sh (what the bootstrap generated). That way the seeds are never written
# by hand and regenerating the identity does not force editing anything.

set -euo pipefail
cd "$(dirname "$0")/.."

REPO_ROOT="$PWD"
NATS_DIR="$REPO_ROOT/nats"

command -v nats-server >/dev/null 2>&1 || {
  echo "ERROR: nats-server is not on PATH (go install github.com/nats-io/nats-server/v2@latest)" >&2
  exit 1
}

if [[ ! -f "$NATS_DIR/out/callout-env.sh" ]]; then
  echo "ERROR: the NATS identity is missing. Run this first: make bootstrap" >&2
  exit 1
fi

# .env is optional: without it the binary's defaults are used (mock mode, dev instance).
if [[ -f "$NATS_DIR/.env" ]]; then
  set -a; . "$NATS_DIR/.env"; set +a
fi

# The contract's paths are relative to nats/, so that is where it is anchored.
CALLOUT_NATS_DIR="$NATS_DIR"
export CALLOUT_NATS_DIR
set -a; . "$NATS_DIR/out/callout-env.sh"; set +a

# Templates are resolved relative to rules.yaml, so its path is all that is needed.
export CALLOUT_RULES_PATH="${CALLOUT_RULES_PATH:-$REPO_ROOT/examples/rules.yaml}"
export CALLOUT_NATS_URL="${CALLOUT_NATS_URL:-nats://127.0.0.1:4322}"

# --- authentication events (OPTIONAL) -----------------------------------------------------
# Turned on by setting CALLOUT_EVENTS_SUBJECT in nats/.env. Everything it needs was generated by
# the bootstrap; what is left is the stream, which cannot exist before the server does — and
# which the CALLOUT deliberately cannot create. So the dev admin credential creates it below,
# the same division of labour a real deployment has.
if [[ -n "${CALLOUT_EVENTS_SUBJECT:-}" ]]; then
  export CALLOUT_EVENTS_CREDS="$NATS_DIR/out/callout-events.creds"
  export CALLOUT_EVENTS_STREAM="${CALLOUT_EVENTS_STREAM:-AUTH_EVENTS}"

  [[ -f "$CALLOUT_EVENTS_CREDS" ]] || {
    echo "ERROR: $CALLOUT_EVENTS_CREDS is missing. Regenerate the identity: rm -rf nats/out && make bootstrap" >&2
    exit 1
  }
  command -v nats >/dev/null 2>&1 || {
    echo "ERROR: the authentication events need the nats CLI to create their stream." >&2
    echo "       Install it (go install github.com/nats-io/natscli/nats@latest) or unset CALLOUT_EVENTS_SUBJECT in nats/.env." >&2
    exit 1
  }

  # The stream's subject. {{instance}} is expanded here the same way the service expands it, so
  # the .env can hold the same pattern the documentation shows.
  EVENTS_SUBJECT="${CALLOUT_EVENTS_SUBJECT//\{\{instance\}\}/${CALLOUT_INSTANCE:-dev}}"
fi

echo "==> Starting nats-server"
mkdir -p "$NATS_DIR/data"
(cd "$NATS_DIR" && nats-server -c nats-server.conf) &
NATS_PID=$!

# Only the nats-server THIS script started gets killed. A nats-server or a callout left over
# from a previous run is NOT touched — and those are the most common cause of "I changed the
# config and nothing happened": the old one keeps serving the callout subject while the new one
# could not bind the port.
cleanup() {
  echo
  echo "==> Stopping nats-server ($NATS_PID)"
  kill "$NATS_PID" 2>/dev/null || true
  wait "$NATS_PID" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

echo "==> Waiting for NATS to accept connections"
for _ in $(seq 1 50); do
  if curl -fsS "http://127.0.0.1:${NATS_MONITOR_PORT:-8322}/healthz" >/dev/null 2>&1; then
    break
  fi
  sleep 0.2
done

if [[ -n "${CALLOUT_EVENTS_SUBJECT:-}" ]]; then
  echo "==> Authentication events: stream $CALLOUT_EVENTS_STREAM over $EVENTS_SUBJECT"
  NATS_ADMIN=(nats --server "$CALLOUT_NATS_URL" --creds "$NATS_DIR/out/app-admin.creds")
  if "${NATS_ADMIN[@]}" stream info "$CALLOUT_EVENTS_STREAM" >/dev/null 2>&1; then
    echo "    (already there)"
  else
    # --dupe-window is what makes retrying an event whose ack was lost idempotent: the publisher
    # sends the connection's user nkey as the message id, and the server collapses a repeat.
    "${NATS_ADMIN[@]}" stream add "$CALLOUT_EVENTS_STREAM" \
      --subjects "$EVENTS_SUBJECT" \
      --storage file --retention limits --discard old \
      --max-age 30d --dupe-window 2m --replicas 1 \
      --max-msgs=-1 --max-msgs-per-subject=-1 --max-bytes=-1 --max-msg-size=-1 \
      --no-allow-rollup --no-deny-delete --no-deny-purge --defaults >/dev/null
    echo "    created"
  fi
fi

echo "==> Starting the callout"
exec go run ./cmd/callout
